import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from '@next/font/local'

const inter = Inter({ subsets: ["latin"] });
const switzer = localFont({ src: '/fonts/Switzer-Variable.woff' })

export const metadata: Metadata = {
  title: "Circles Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={switzer.className}>{children}</body>
    </html>
  );
}
